---
- name: 3560CX IOS UPGRADE TO 15.2.7(E6)
  hosts: test_switches
  connection: network_cli
  gather_facts: false

  vars:
   - new_ios_bin: c3560cx-universalk9-mz.152-7.E6.bin
   - new_ios_md5: 1d3c6f78f7df594ae4bdd9faa16ee6de
   - tac1_name: NSKISETACPSN
   - tac1_ip: 10.26.60.20
   - tac2_name: BVLISETACPSN
   - tac2_ip: 158.139.170.16
   - tac3_name: CQ9ISETACPSN
   - tac3_ip: 155.191.182.137
   - tac_key: !vault |
       $ANSIBLE_VAULT;1.1;AES256
       36633362323530373163323038653063353463303035626664646231343530303234666636636433
       6135353834613131623761663938343333643963303234370a313237613638363435656538306162
       36343265313266306636333632313933363733303133613137393864616631363865313462636432
       6465643633343664350a376261343866613466303038623636333339633830646533333736393533
       39616165623735666435646139323735623438643165353263386633306338373238

  tasks:
    - name: REMOVE OLD TAC COMMANDS
      block:
        - set_fact:
            oldtac1: "{{ tac_out.stdout_lines[0][0] }}"
          when: tac_out.stdout_lines[0][0] is defined
        - set_fact:
            oldtac2: "{{ tac_out.stdout_lines[0][1] }}"
          when: tac_out.stdout_lines[0][1] is search('tacacs-server host')
        - set_fact:
            oldtac3: "{{ tac_out.stdout_lines[0][2] }}"
          when: tac_out.stdout_lines[0][2] is defined
        - name: REMOVE TACACS-SERVER KEY
          cisco.ios.ios_config:
            lines: no tacacs-server key
        - name: REMOVE SERVER 1 IF PRESENT
          cisco.ios.ios_config:
            lines: no {{ oldtac1 }}
          when: oldtac1 is defined
        - name: REMOVE SERVER 2 IF PRESENT
          cisco.ios.ios_config:
            lines: no {{ oldtac2 }}
          when: oldtac2 is defined
        - name: REMOVE SERVER 3 IF PRESENT
          cisco.ios.ios_config:
            lines: no {{ oldtac3 }}
          when: oldtac3 is defined

        - name: CONFIGURE TACACS SERVERS
          block:
            - name: CONFIGURE TACACS SERVER-1
              cisco.ios.ios_config:
                lines:
                  - address ipv4 {{ tac1_ip }}
                  - "{{ tac_key }}"
                parents: tacacs server {{ tac1_name }}
                before: no tacacs server {{ tac1_name }}
                match: exact
                replace: block
            - name: CONFIGURE TACACS SERVER-2
              cisco.ios.ios_config:
                lines:
                  - address ipv4 {{ tac2_ip }}
                  - "{{ tac_key }}"
                parents: tacacs server {{ tac2_name }}
                before: no tacacs server {{ tac2_name }}
                match: exact
                replace: block
            - name: CONFIGURE TACACS SERVER-3
              cisco.ios.ios_config:
                lines:
                  - address ipv4 {{ tac3_ip }}
                  - "{{ tac_key }}"
                parents: tacacs server {{ tac3_name }}
                before: no tacacs server {{ tac3_name }}
                match: exact
                replace: block
                save_when: modified
      when: tac_out is search('tacacs-server host')

    - name: COPY OVER IOS IMAGE
      ios_command:
        commands:
          - command: 'copy tftp://10.27.18.14/{{ new_ios_bin }} flash:'
            prompt: 'Destination filename \[{{ new_ios_bin }}\]?'
            answer: "\r"
      vars:
        ansible_command_timeout: 600

    - name: VERIFY MD5
      ios_command:
        commands:
          - "verify /md5 flash:{{ new_ios_bin }}"
        wait_for: result[0] contains "{{ new_ios_md5 }}"
        retries: 1
      vars:
        ansible_command_timeout: 140
    - debug:
        msg: "Md5 Verified!"

    - name: CONTINUE UPGRADE IF MD5 HASH MATCHES
      block:
      - name: SETTING BOOT IMAGE
        cisco.ios.ios_config:
          lines:
          - boot system flash:{{ new_ios_bin }}
          match: none
          save_when: always

    - name: ISSUE RELOAD COMMAND
      cli_command:
        command: reload
        prompt: '\[confirm\]'
        answer: "\r"

    - name: BREAK CONNECTION FOR IMDEMPOTENCY
      meta: reset_connection

    - name: WAIT FOR LIFE
      wait_for_connection:
        delay: 10

    - name: UPTIME CONFIRMATION
      cli_command:
        command: show ver | i .ptime
      register: uptime

    - debug:
        msg: "{{uptime.stdout}}"

    - name: GATHER FACTS
      ios_facts:
        gather_subset:

    - name: ASSERT THAT THE IOS VERSION IS CORRECT
      assert:
        that:
          - {{new_ios_bin}} == {{ansible_net_version}}
        msg: "{{ansible_net_hostname}} has been upgraded to {{new_ios_bin}}"
...
