---
- name: SET BOOT VARIABLE
  hosts: test_switches
  connection: network_cli
  gather_facts: no

  vars:
    - new_ios_bin: c3560cx-universalk9-mz.152-7.E6.bin

  tasks:
    - name: SETTING BOOT IMAGE
      cisco.ios.ios_config:
        lines: boot system flash:{{ new_ios_bin }}
        match: line
      register: output
    - debug:
        var: output

    - name: SAVE IF MODIFIED
      cisco.ios.ios_config:
        save_when: modified

# TODO move save_when into - name: SETTING BOOT IMAGE
# TODO match: line or none
