---
- name: RELOAD DEVICE AND WAIT FOR REBIRTH
  hosts: test_switches
  connection: network_cli
  gather_facts: false

  tasks:
    - name: WRITE TO STARTUP_CONFIG
      ios_command:
        command: 'write memory'

    - name: REBOOT SWITCH IF INSTRUCTED
      cli_command:
        commands: reload
        prompt: '\[confirm\]'
        answer: "\r"

    - name: reset the connection
      meta: reset_connection

    - name: wait for network device to come back up
      wait_for_connection:
        delay: 10

    - name: grab the uptime
      cli_command:
        command: show ver | i Uptime
      register: uptime

    - name: show uptime
      debug:
        msg: "{{uptime.stdout}}"
