---
- name: RELOAD DEVICE AND WAIT FOR REBIRTH
  hosts: test_switches
  connection: network_cli
  gather_facts: false

  tasks:
    - name: WRITE TO STARTUP_CONFIG
      ios_command:
        commands: 'write memory'

    - name: ISSUE RELOAD COMMAND
      cli_command:
        command: reload
        prompt: '\[confirm\]'
        answer: "\r"

    - name: BREAK CONNECTION FOR IMDEMPOTENCY
      meta: reset_connection

    - name: WAIT FOR LIFE
      wait_for_connection:
        delay: 10

    - name: UPTIME CONFIRMATION
      cli_command:
        command: show ver | i .ptime
      register: uptime

    - debug:
        msg: "{{uptime.stdout}}"
