---
- name: ADD NEW-STYLE TACACS CONFIGURATION
  hosts: test_switch
  connection: network_cli
  gather_facts: no

  vars:
    - tac1_name: NSKISETACPSN
    - tac1_ip: 10.26.60.20
    - tac2_name: BVLISETACPSN
    - tac2_ip: 158.139.170.16
    - tac3_name: CQ9ISETACPSN
    - tac3_ip: 155.191.182.137
    - tacacs_key: "{{ vault_tacacs_key }}"
      
  tasks:
    - name: REMOVE LEGACY TACACS COMMAND
      ios_config:
        lines:
          - no tacacs-server host 10.26.60.20
          - no tacacs-server host 158.139.170.16
          - no tacacs-server host 155.191.182.137
        save_when: modified
    - name: CONFIGURE TACACS SERVER-1
      ios_config:
        lines:
          - address ipv4 {{ tac1_ip }}
          - key {{ tacacs_key }}
        parents: tacacs server {{ tac1_name }}
        match: line
        save_when: modified
    - name: CONFIGURE TACACS SERVER-2
      ios_config:
        lines:
          - address ipv4 {{ tac2_ip }}
          - key {{ tacacs_key }}
        parents: tacacs server {{ tac2_name }}
        match: line
        save_when: modified
    - name: CONFIGURE TACACS SERVER-3
      ios_config:
        lines:
          - address ipv4 {{ tac3_ip }}
          - key {{ tacacs_key }}
        parents: tacacs server {{ tac3_name }}
        match: line
        save_when: modified