---
- name: UPDATE VTY/EN PASSWORDS
  hosts: test_switches
  connection: network_cli
  gather_facts: false

  tasks:
    - name: UPDATE ENABLE SECRET
      ios_config:
        lines:
          - enable algo scrypt secret {{enable_secret_09_22}}
          - username tombstone priv 15 algo scrypt secret {{enable_secret_09_22}}
      register: output

    - name: CONFIGURE CONSOLE PASSWORD
      cisco.ios.ios_config:
        lines:
          - "{{vty_password_09_22}}"
        parents: line con 0
        match: none

    - name: CONFIGURE VTY 0 4 PASSWORD
      cisco.ios.ios_config:
        lines:
          - "{{vty_password_09_22}}"
        parents: line vty 0 4
        match: none

    - name: CONFIGURE VTY 5 15 PASSWORD
      cisco.ios.ios_config:
        lines:
          - "{{vty_password_09_22}}"
        parents: line vty 5 15
        match: none